destination: ./docs

# Site metadata — consumed by structured data and SEO meta tags.
url: "https://cosimocomparini-psicologo.it"
title: "Psicologo a Cesena e Gambettola"

defaults:
  -
    # default layout for all pages
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  -
    # default layout for all posts
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-optional-front-matter # Markdown files to not require front matter

# jekyll-optional-front-matter
optional_front_matter:
  remove_originals: true

# Order of these matter!
# (For example: `home_sections` uses `quotes`, therefore `quotes` is positioned
# before `home_sections`.)
collections:
  posts:
    permalink: /articoli/:title
  quotes:
  home_sections:
    order:
      - quando-chiedere-aiuto.md
      - sintomo.md
      - trattamento.md
  aree-di-intervento_sections:
    order:
      - disturbi-di-ansia.md
      - disturbi-ossessivo-compulsivi.md
      - disturbi-dell-umore.md
      - disturbi-alimentari.md
      - disturbi-di-personalita.md
      - disturbi-somatoformi.md
      - dipendenze-patologiche.md
      - disagi-dell-infanzia-e-dell-adolescenza.md
      - problemi-di-relazione.md
      - disfunzioni-della-sfera-sessuale.md

exclude:
  - '/*.config.js'
  - /assetchecksum.sh
  - /package*.json
  - /script/
